services:
    mattf.pwakit.listener:
        class: mattf\pwakit\event\main_listener
        arguments:
            - '@config'
            - '@mattf.pwakit.helper'
            - '@template'
        tags:
            - { name: event.listener }

    mattf.pwakit.helper:
        class: mattf\pwakit\helper\helper
        arguments:
            - '@cache.driver'
            - '@ext.manager'
            - '@upload_imagesize'
            - '%core.root_path%'

    mattf.pwakit.upload:
        class: mattf\pwakit\helper\upload
        arguments:
            - '@files.upload'
            - '@filesystem'
