services:
    phpbb.pwakit.listener:
        class: phpbb\pwakit\event\main_listener
        arguments:
            - '@phpbb.pwakit.helper'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }

    phpbb.pwakit.helper:
        class: phpbb\pwakit\helper\helper
        arguments:
            - '@ext.manager'
            - '@upload_imagesize'
            - '@phpbb.pwakit.storage'
            - '@storage.helper'
            - '@storage.provider_collection'
            - '%core.root_path%'

    phpbb.pwakit.upload:
        class: phpbb\pwakit\helper\upload
        arguments:
            - '@files.upload'
            - '@phpbb.pwakit.storage'

    phpbb.pwakit.storage:
        class: phpbb\pwakit\storage\storage
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@storage.adapter.factory'
            - 'phpbb_pwakit'
            - '%tables.storage%'
        tags:
            - { name: storage }

    phpbb.pwakit.admin.controller:
        class: phpbb\pwakit\controller\admin_controller
        arguments:
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@phpbb.pwakit.helper'
            - '@phpbb.pwakit.upload'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
