name: Tests

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
            - master
            - develop
            - dev/*
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main
            - master
            - develop
            - dev/*

jobs:
    call-tests:
        uses: iMattPro/test-framework/.github/workflows/tests.yml@experiment-master
        with:
            EXTNAME: phpbb/pwakit   # Your extension vendor/package name
            RUN_MSSQL_JOBS: 0
            RUN_PGSQL_JOBS: 0
            RUN_MYSQL_JOBS: 0
            EPV: 0
            SNIFF: 0
            IMAGE_ICC: 0
            EXECUTABLE_FILES: 0
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Do not change this
